import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Navbar } from "../Components/Navbar";
import { Header } from "../Components/Header";
import { Main } from "../Components/Main";
import { Section } from "../Components/Section";
import { Footer } from "../Components/Footer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Header />
      <Main />
      <Section />
      <Footer />
    </div>
  );
}
